// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: audit.sql

package sqlcdb

import (
	"context"
	"time"
)

const countAuditEntries = `-- name: CountAuditEntries :one
SELECT COUNT(*) FROM audit_log
`

func (q *Queries) CountAuditEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuditEntries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditEntry = `-- name: CreateAuditEntry :exec
INSERT INTO audit_log (id, timestamp, action, actor_type, actor_id, resource_type, resource_id, details)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAuditEntryParams struct {
	ID           string
	Timestamp    time.Time
	Action       string
	ActorType    string
	ActorID      string
	ResourceType string
	ResourceID   string
	Details      string
}

func (q *Queries) CreateAuditEntry(ctx context.Context, arg CreateAuditEntryParams) error {
	_, err := q.db.ExecContext(ctx, createAuditEntry,
		arg.ID,
		arg.Timestamp,
		arg.Action,
		arg.ActorType,
		arg.ActorID,
		arg.ResourceType,
		arg.ResourceID,
		arg.Details,
	)
	return err
}

const listAuditEntries = `-- name: ListAuditEntries :many
SELECT id, timestamp, action, actor_type, actor_id, resource_type, resource_id, details
FROM audit_log ORDER BY timestamp DESC LIMIT ? OFFSET ?
`

type ListAuditEntriesParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListAuditEntries(ctx context.Context, arg ListAuditEntriesParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEntries, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Action,
			&i.ActorType,
			&i.ActorID,
			&i.ResourceType,
			&i.ResourceID,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
