// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: environments.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"time"
)

const countEnvironments = `-- name: CountEnvironments :one
SELECT COUNT(*) FROM environments
`

func (q *Queries) CountEnvironments(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEnvironments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEnvironment = `-- name: CreateEnvironment :exec
INSERT INTO environments (id, project, environment, created_at) VALUES (?, ?, ?, ?)
`

type CreateEnvironmentParams struct {
	ID          string
	Project     string
	Environment string
	CreatedAt   time.Time
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) error {
	_, err := q.db.ExecContext(ctx, createEnvironment,
		arg.ID,
		arg.Project,
		arg.Environment,
		arg.CreatedAt,
	)
	return err
}

const deleteEnvironment = `-- name: DeleteEnvironment :execresult
DELETE FROM environments WHERE id = ?
`

func (q *Queries) DeleteEnvironment(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteEnvironment, id)
}

const environmentInUsePolicies = `-- name: EnvironmentInUsePolicies :one
SELECT COUNT(*) FROM access_policies WHERE environment_id = ?
`

func (q *Queries) EnvironmentInUsePolicies(ctx context.Context, environmentID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, environmentInUsePolicies, environmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const environmentInUseSecrets = `-- name: EnvironmentInUseSecrets :one
SELECT COUNT(*) FROM secrets WHERE environment_id = ?
`

func (q *Queries) EnvironmentInUseSecrets(ctx context.Context, environmentID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, environmentInUseSecrets, environmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT id, project, environment, created_at FROM environments WHERE id = ?
`

func (q *Queries) GetEnvironment(ctx context.Context, id string) (Environment, error) {
	row := q.db.QueryRowContext(ctx, getEnvironment, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.Project,
		&i.Environment,
		&i.CreatedAt,
	)
	return i, err
}

const insertEnvironmentIgnore = `-- name: InsertEnvironmentIgnore :exec
INSERT OR IGNORE INTO environments (id, project, environment) VALUES (?, ?, ?)
`

type InsertEnvironmentIgnoreParams struct {
	ID          string
	Project     string
	Environment string
}

func (q *Queries) InsertEnvironmentIgnore(ctx context.Context, arg InsertEnvironmentIgnoreParams) error {
	_, err := q.db.ExecContext(ctx, insertEnvironmentIgnore, arg.ID, arg.Project, arg.Environment)
	return err
}

const listEnvironments = `-- name: ListEnvironments :many
SELECT id, project, environment, created_at FROM environments ORDER BY project, environment
`

func (q *Queries) ListEnvironments(ctx context.Context) ([]Environment, error) {
	rows, err := q.db.QueryContext(ctx, listEnvironments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.Project,
			&i.Environment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnvironment = `-- name: UpdateEnvironment :execresult
UPDATE environments SET project = ?, environment = ? WHERE id = ?
`

type UpdateEnvironmentParams struct {
	Project     string
	Environment string
	ID          string
}

func (q *Queries) UpdateEnvironment(ctx context.Context, arg UpdateEnvironmentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateEnvironment, arg.Project, arg.Environment, arg.ID)
}
