// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: machine_tokens.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"time"
)

const countMachineTokens = `-- name: CountMachineTokens :one
SELECT COUNT(*) FROM machine_tokens
`

func (q *Queries) CountMachineTokens(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMachineTokens)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMachineToken = `-- name: CreateMachineToken :exec
INSERT INTO machine_tokens (id, name, token_hash, token_prefix, policy_id, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateMachineTokenParams struct {
	ID          string
	Name        string
	TokenHash   string
	TokenPrefix string
	PolicyID    string
	CreatedAt   time.Time
}

func (q *Queries) CreateMachineToken(ctx context.Context, arg CreateMachineTokenParams) error {
	_, err := q.db.ExecContext(ctx, createMachineToken,
		arg.ID,
		arg.Name,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.PolicyID,
		arg.CreatedAt,
	)
	return err
}

const deleteMachineToken = `-- name: DeleteMachineToken :execresult
DELETE FROM machine_tokens WHERE id = ?
`

func (q *Queries) DeleteMachineToken(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteMachineToken, id)
}

const getMachineTokenByHash = `-- name: GetMachineTokenByHash :one
SELECT t.id, t.name, t.token_prefix, t.policy_id, p.name AS policy_name, t.created_at, t.last_used_at
FROM machine_tokens t
JOIN access_policies p ON p.id = t.policy_id
WHERE t.token_hash = ?
`

type GetMachineTokenByHashRow struct {
	ID          string
	Name        string
	TokenPrefix string
	PolicyID    string
	PolicyName  string
	CreatedAt   time.Time
	LastUsedAt  sql.NullTime
}

func (q *Queries) GetMachineTokenByHash(ctx context.Context, tokenHash string) (GetMachineTokenByHashRow, error) {
	row := q.db.QueryRowContext(ctx, getMachineTokenByHash, tokenHash)
	var i GetMachineTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenPrefix,
		&i.PolicyID,
		&i.PolicyName,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listMachineTokens = `-- name: ListMachineTokens :many
SELECT t.id, t.name, t.token_prefix, t.policy_id, p.name AS policy_name, t.created_at, t.last_used_at
FROM machine_tokens t
JOIN access_policies p ON p.id = t.policy_id
ORDER BY t.created_at DESC
`

type ListMachineTokensRow struct {
	ID          string
	Name        string
	TokenPrefix string
	PolicyID    string
	PolicyName  string
	CreatedAt   time.Time
	LastUsedAt  sql.NullTime
}

func (q *Queries) ListMachineTokens(ctx context.Context) ([]ListMachineTokensRow, error) {
	rows, err := q.db.QueryContext(ctx, listMachineTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMachineTokensRow
	for rows.Next() {
		var i ListMachineTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenPrefix,
			&i.PolicyID,
			&i.PolicyName,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchMachineToken = `-- name: TouchMachineToken :exec
UPDATE machine_tokens SET last_used_at = ? WHERE id = ?
`

type TouchMachineTokenParams struct {
	LastUsedAt sql.NullTime
	ID         string
}

func (q *Queries) TouchMachineToken(ctx context.Context, arg TouchMachineTokenParams) error {
	_, err := q.db.ExecContext(ctx, touchMachineToken, arg.LastUsedAt, arg.ID)
	return err
}
