// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcdb

import (
	"database/sql"
	"time"
)

type AccessPolicy struct {
	ID                 string
	Name               string
	RepositoryPatterns string
	RefPatterns        string
	ActorPatterns      string
	EnvironmentID      string
	CreatedAt          time.Time
}

type AuditLog struct {
	ID           string
	Timestamp    time.Time
	Action       string
	ActorType    string
	ActorID      string
	ResourceType string
	ResourceID   string
	Details      string
}

type Environment struct {
	ID          string
	Project     string
	Environment string
	CreatedAt   time.Time
}

type MachineToken struct {
	ID            string
	Name          string
	TokenHash     string
	TokenPrefix   string
	EnvironmentID string
	CreatedAt     time.Time
	LastUsedAt    sql.NullTime
}

type Secret struct {
	ID            string
	Key           string
	Value         []byte
	EnvironmentID string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
