// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"database/sql"
	"time"
)

type AccessPolicy struct {
	ID        string
	Name      string
	CreatedAt time.Time
}

type AuditLog struct {
	ID           string
	Timestamp    time.Time
	Action       string
	ActorType    string
	ActorID      string
	ResourceType string
	ResourceID   string
	Details      string
}

type GithubPushProvenance struct {
	Repository     string
	Ref            string
	Sha            string
	GithubUserID   string
	GithubLogin    string
	MachineTokenID string
	AttestedAt     time.Time
}

type MachineToken struct {
	ID                    string
	Name                  string
	TokenHash             string
	TokenPrefix           string
	PolicyID              sql.NullString
	CanAttestGithubPushes int64
	CreatedAt             time.Time
	LastUsedAt            sql.NullTime
}

type MachineTokenNode struct {
	TokenID string
	NodeID  string
}

type PolicyPattern struct {
	PolicyID string
	Kind     string
	Pattern  string
}

type PolicyPrecedence struct {
	NodeID      string
	PolicyID    string
	DependsOnID string
}

type SecretNode struct {
	ID        string
	Kind      string
	ParentID  sql.NullString
	Name      string
	Value     []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SecretNodePolicy struct {
	NodeID   string
	PolicyID string
}
