// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policy_patterns.sql

package sqlcdb

import (
	"context"
)

const deleteAllPolicyPatterns = `-- name: DeleteAllPolicyPatterns :exec
DELETE FROM policy_patterns WHERE policy_id = ?
`

func (q *Queries) DeleteAllPolicyPatterns(ctx context.Context, policyID string) error {
	_, err := q.db.ExecContext(ctx, deleteAllPolicyPatterns, policyID)
	return err
}

const deletePolicyPatternsOfKind = `-- name: DeletePolicyPatternsOfKind :exec
DELETE FROM policy_patterns WHERE policy_id = ? AND kind = ?
`

type DeletePolicyPatternsOfKindParams struct {
	PolicyID string
	Kind     string
}

func (q *Queries) DeletePolicyPatternsOfKind(ctx context.Context, arg DeletePolicyPatternsOfKindParams) error {
	_, err := q.db.ExecContext(ctx, deletePolicyPatternsOfKind, arg.PolicyID, arg.Kind)
	return err
}

const insertPolicyPattern = `-- name: InsertPolicyPattern :exec
INSERT INTO policy_patterns (policy_id, kind, pattern) VALUES (?, ?, ?)
`

type InsertPolicyPatternParams struct {
	PolicyID string
	Kind     string
	Pattern  string
}

func (q *Queries) InsertPolicyPattern(ctx context.Context, arg InsertPolicyPatternParams) error {
	_, err := q.db.ExecContext(ctx, insertPolicyPattern, arg.PolicyID, arg.Kind, arg.Pattern)
	return err
}

const listPolicyPatterns = `-- name: ListPolicyPatterns :many
SELECT policy_id, kind, pattern
FROM policy_patterns
WHERE policy_id = ?
ORDER BY kind, pattern
`

func (q *Queries) ListPolicyPatterns(ctx context.Context, policyID string) ([]PolicyPattern, error) {
	rows, err := q.db.QueryContext(ctx, listPolicyPatterns, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolicyPattern
	for rows.Next() {
		var i PolicyPattern
		if err := rows.Scan(&i.PolicyID, &i.Kind, &i.Pattern); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
