// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: policies.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"time"
)

const countPolicies = `-- name: CountPolicies :one
SELECT COUNT(*) FROM access_policies
`

func (q *Queries) CountPolicies(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPolicies)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPolicy = `-- name: CreatePolicy :exec
INSERT INTO access_policies (id, name, mode, repository_patterns, ref_patterns, actor_patterns, github_environment, environment_id, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePolicyParams struct {
	ID                 string
	Name               string
	Mode               string
	RepositoryPatterns string
	RefPatterns        string
	ActorPatterns      string
	GithubEnvironment  string
	EnvironmentID      string
	CreatedAt          time.Time
}

func (q *Queries) CreatePolicy(ctx context.Context, arg CreatePolicyParams) error {
	_, err := q.db.ExecContext(ctx, createPolicy,
		arg.ID,
		arg.Name,
		arg.Mode,
		arg.RepositoryPatterns,
		arg.RefPatterns,
		arg.ActorPatterns,
		arg.GithubEnvironment,
		arg.EnvironmentID,
		arg.CreatedAt,
	)
	return err
}

const deletePolicy = `-- name: DeletePolicy :execresult
DELETE FROM access_policies WHERE id = ?
`

func (q *Queries) DeletePolicy(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deletePolicy, id)
}

const getPolicy = `-- name: GetPolicy :one
SELECT p.id, p.name, p.mode, p.repository_patterns, p.ref_patterns, p.actor_patterns, p.github_environment, p.environment_id, e.project, e.environment, p.created_at
FROM access_policies p
JOIN environments e ON e.id = p.environment_id
WHERE p.id = ?
`

type GetPolicyRow struct {
	ID                 string
	Name               string
	Mode               string
	RepositoryPatterns string
	RefPatterns        string
	ActorPatterns      string
	GithubEnvironment  string
	EnvironmentID      string
	Project            string
	Environment        string
	CreatedAt          time.Time
}

func (q *Queries) GetPolicy(ctx context.Context, id string) (GetPolicyRow, error) {
	row := q.db.QueryRowContext(ctx, getPolicy, id)
	var i GetPolicyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Mode,
		&i.RepositoryPatterns,
		&i.RefPatterns,
		&i.ActorPatterns,
		&i.GithubEnvironment,
		&i.EnvironmentID,
		&i.Project,
		&i.Environment,
		&i.CreatedAt,
	)
	return i, err
}

const listPolicies = `-- name: ListPolicies :many
SELECT p.id, p.name, p.mode, p.repository_patterns, p.ref_patterns, p.actor_patterns, p.github_environment, p.environment_id, e.project, e.environment, p.created_at
FROM access_policies p
JOIN environments e ON e.id = p.environment_id
ORDER BY p.name
`

type ListPoliciesRow struct {
	ID                 string
	Name               string
	Mode               string
	RepositoryPatterns string
	RefPatterns        string
	ActorPatterns      string
	GithubEnvironment  string
	EnvironmentID      string
	Project            string
	Environment        string
	CreatedAt          time.Time
}

func (q *Queries) ListPolicies(ctx context.Context) ([]ListPoliciesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPoliciesRow
	for rows.Next() {
		var i ListPoliciesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Mode,
			&i.RepositoryPatterns,
			&i.RefPatterns,
			&i.ActorPatterns,
			&i.GithubEnvironment,
			&i.EnvironmentID,
			&i.Project,
			&i.Environment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePolicy = `-- name: UpdatePolicy :execresult
UPDATE access_policies SET name = ?, mode = ?, repository_patterns = ?, ref_patterns = ?, actor_patterns = ?, github_environment = ?, environment_id = ?
WHERE id = ?
`

type UpdatePolicyParams struct {
	Name               string
	Mode               string
	RepositoryPatterns string
	RefPatterns        string
	ActorPatterns      string
	GithubEnvironment  string
	EnvironmentID      string
	ID                 string
}

func (q *Queries) UpdatePolicy(ctx context.Context, arg UpdatePolicyParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updatePolicy,
		arg.Name,
		arg.Mode,
		arg.RepositoryPatterns,
		arg.RefPatterns,
		arg.ActorPatterns,
		arg.GithubEnvironment,
		arg.EnvironmentID,
		arg.ID,
	)
}
