// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: secrets.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"time"
)

const countSecrets = `-- name: CountSecrets :one
SELECT COUNT(*) FROM secrets
`

func (q *Queries) CountSecrets(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSecrets)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSecret = `-- name: CreateSecret :exec
INSERT INTO secrets (id, key, value, environment_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateSecretParams struct {
	ID            string
	Key           string
	Value         []byte
	EnvironmentID string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) CreateSecret(ctx context.Context, arg CreateSecretParams) error {
	_, err := q.db.ExecContext(ctx, createSecret,
		arg.ID,
		arg.Key,
		arg.Value,
		arg.EnvironmentID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteSecret = `-- name: DeleteSecret :execresult
DELETE FROM secrets WHERE id = ?
`

func (q *Queries) DeleteSecret(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteSecret, id)
}

const getSecret = `-- name: GetSecret :one
SELECT s.id, s.key, s.value, s.environment_id, e.project, e.environment, s.created_at, s.updated_at
FROM secrets s
JOIN environments e ON e.id = s.environment_id
WHERE s.id = ?
`

type GetSecretRow struct {
	ID            string
	Key           string
	Value         []byte
	EnvironmentID string
	Project       string
	Environment   string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) GetSecret(ctx context.Context, id string) (GetSecretRow, error) {
	row := q.db.QueryRowContext(ctx, getSecret, id)
	var i GetSecretRow
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.EnvironmentID,
		&i.Project,
		&i.Environment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSecretsByEnvironmentID = `-- name: GetSecretsByEnvironmentID :many
SELECT key, value FROM secrets WHERE environment_id = ?
`

type GetSecretsByEnvironmentIDRow struct {
	Key   string
	Value []byte
}

func (q *Queries) GetSecretsByEnvironmentID(ctx context.Context, environmentID string) ([]GetSecretsByEnvironmentIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getSecretsByEnvironmentID, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSecretsByEnvironmentIDRow
	for rows.Next() {
		var i GetSecretsByEnvironmentIDRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretsAll = `-- name: ListSecretsAll :many
SELECT s.id, s.key, s.environment_id, e.project, e.environment, s.created_at, s.updated_at
FROM secrets s
JOIN environments e ON e.id = s.environment_id
ORDER BY e.project, e.environment, s.key
`

type ListSecretsAllRow struct {
	ID            string
	Key           string
	EnvironmentID string
	Project       string
	Environment   string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) ListSecretsAll(ctx context.Context) ([]ListSecretsAllRow, error) {
	rows, err := q.db.QueryContext(ctx, listSecretsAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSecretsAllRow
	for rows.Next() {
		var i ListSecretsAllRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.EnvironmentID,
			&i.Project,
			&i.Environment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretsByEnv = `-- name: ListSecretsByEnv :many
SELECT s.id, s.key, s.environment_id, e.project, e.environment, s.created_at, s.updated_at
FROM secrets s
JOIN environments e ON e.id = s.environment_id
WHERE e.environment = ?
ORDER BY e.project, e.environment, s.key
`

type ListSecretsByEnvRow struct {
	ID            string
	Key           string
	EnvironmentID string
	Project       string
	Environment   string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) ListSecretsByEnv(ctx context.Context, environment string) ([]ListSecretsByEnvRow, error) {
	rows, err := q.db.QueryContext(ctx, listSecretsByEnv, environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSecretsByEnvRow
	for rows.Next() {
		var i ListSecretsByEnvRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.EnvironmentID,
			&i.Project,
			&i.Environment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretsByProject = `-- name: ListSecretsByProject :many
SELECT s.id, s.key, s.environment_id, e.project, e.environment, s.created_at, s.updated_at
FROM secrets s
JOIN environments e ON e.id = s.environment_id
WHERE e.project = ?
ORDER BY e.project, e.environment, s.key
`

type ListSecretsByProjectRow struct {
	ID            string
	Key           string
	EnvironmentID string
	Project       string
	Environment   string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) ListSecretsByProject(ctx context.Context, project string) ([]ListSecretsByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listSecretsByProject, project)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSecretsByProjectRow
	for rows.Next() {
		var i ListSecretsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.EnvironmentID,
			&i.Project,
			&i.Environment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretsByProjectAndEnv = `-- name: ListSecretsByProjectAndEnv :many
SELECT s.id, s.key, s.environment_id, e.project, e.environment, s.created_at, s.updated_at
FROM secrets s
JOIN environments e ON e.id = s.environment_id
WHERE e.project = ? AND e.environment = ?
ORDER BY e.project, e.environment, s.key
`

type ListSecretsByProjectAndEnvParams struct {
	Project     string
	Environment string
}

type ListSecretsByProjectAndEnvRow struct {
	ID            string
	Key           string
	EnvironmentID string
	Project       string
	Environment   string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) ListSecretsByProjectAndEnv(ctx context.Context, arg ListSecretsByProjectAndEnvParams) ([]ListSecretsByProjectAndEnvRow, error) {
	rows, err := q.db.QueryContext(ctx, listSecretsByProjectAndEnv, arg.Project, arg.Environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSecretsByProjectAndEnvRow
	for rows.Next() {
		var i ListSecretsByProjectAndEnvRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.EnvironmentID,
			&i.Project,
			&i.Environment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const secretCountsByProjectEnv = `-- name: SecretCountsByProjectEnv :many
SELECT e.project, e.environment, COUNT(*) AS secret_count
FROM secrets s
JOIN environments e ON e.id = s.environment_id
GROUP BY e.project, e.environment
ORDER BY e.project, e.environment
`

type SecretCountsByProjectEnvRow struct {
	Project     string
	Environment string
	SecretCount int64
}

func (q *Queries) SecretCountsByProjectEnv(ctx context.Context) ([]SecretCountsByProjectEnvRow, error) {
	rows, err := q.db.QueryContext(ctx, secretCountsByProjectEnv)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SecretCountsByProjectEnvRow
	for rows.Next() {
		var i SecretCountsByProjectEnvRow
		if err := rows.Scan(&i.Project, &i.Environment, &i.SecretCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSecret = `-- name: UpdateSecret :execresult
UPDATE secrets SET key = ?, value = ?, environment_id = ?, updated_at = ?
WHERE id = ?
`

type UpdateSecretParams struct {
	Key           string
	Value         []byte
	EnvironmentID string
	UpdatedAt     time.Time
	ID            string
}

func (q *Queries) UpdateSecret(ctx context.Context, arg UpdateSecretParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateSecret,
		arg.Key,
		arg.Value,
		arg.EnvironmentID,
		arg.UpdatedAt,
		arg.ID,
	)
}
