// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: secret_nodes.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const authorizedSecrets = `-- name: AuthorizedSecrets :many
WITH RECURSIVE authorized(id) AS (
    SELECT snp.node_id
    FROM secret_node_policies snp
    WHERE snp.policy_id IN (/*SLICE:policy_ids*/?)
    UNION
    SELECT sn.id
    FROM secret_nodes sn
    JOIN authorized a ON sn.parent_id = a.id
)
SELECT sn.id, sn.name, sn.value
FROM secret_nodes sn
JOIN authorized a ON sn.id = a.id
WHERE sn.kind = 'secret'
`

type AuthorizedSecretsRow struct {
	ID    string
	Name  string
	Value []byte
}

// AuthorizedSecrets returns every leaf secret reachable from any of the given
// policy IDs via a downward walk through attached nodes. A policy attached to
// a group grants access to the whole subtree beneath it.
func (q *Queries) AuthorizedSecrets(ctx context.Context, policyIds []string) ([]AuthorizedSecretsRow, error) {
	query := authorizedSecrets
	var queryParams []interface{}
	if len(policyIds) > 0 {
		for _, v := range policyIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:policy_ids*/?", strings.Repeat(",?", len(policyIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:policy_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthorizedSecretsRow
	for rows.Next() {
		var i AuthorizedSecretsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const authorizedSecretsForToken = `-- name: AuthorizedSecretsForToken :many
WITH RECURSIVE authorized(id) AS (
    SELECT mtn.node_id
    FROM machine_token_nodes mtn
    WHERE mtn.token_id = ?1
    UNION
    SELECT snp.node_id
    FROM secret_node_policies snp
    JOIN machine_tokens mt ON mt.policy_id = snp.policy_id
    WHERE mt.id = ?1
    UNION
    SELECT sn.id
    FROM secret_nodes sn
    JOIN authorized a ON sn.parent_id = a.id
)
SELECT sn.id, sn.name, sn.value
FROM secret_nodes sn
JOIN authorized a ON sn.id = a.id
WHERE sn.kind = 'secret'
`

type AuthorizedSecretsForTokenRow struct {
	ID    string
	Name  string
	Value []byte
}

// AuthorizedSecretsForToken returns every leaf secret a machine token may read:
// the union of its direct node attachments (machine_token_nodes) and the nodes
// granted by its optional bound policy (secret_node_policies via policy_id),
// each expanded down through any attached group's subtree. Same downward walk as
// AuthorizedSecrets, just seeded from both sources; a token with no policy
// contributes nothing from the policy branch.
func (q *Queries) AuthorizedSecretsForToken(ctx context.Context, tokenID string) ([]AuthorizedSecretsForTokenRow, error) {
	rows, err := q.db.QueryContext(ctx, authorizedSecretsForToken, tokenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthorizedSecretsForTokenRow
	for rows.Next() {
		var i AuthorizedSecretsForTokenRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countNodesByKind = `-- name: CountNodesByKind :one
SELECT COUNT(*) FROM secret_nodes WHERE kind = ?
`

func (q *Queries) CountNodesByKind(ctx context.Context, kind string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNodesByKind, kind)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSecretNode = `-- name: CreateSecretNode :exec
INSERT INTO secret_nodes (id, kind, parent_id, name, value, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateSecretNodeParams struct {
	ID        string
	Kind      string
	ParentID  sql.NullString
	Name      string
	Value     []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateSecretNode(ctx context.Context, arg CreateSecretNodeParams) error {
	_, err := q.db.ExecContext(ctx, createSecretNode,
		arg.ID,
		arg.Kind,
		arg.ParentID,
		arg.Name,
		arg.Value,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteSecretNode = `-- name: DeleteSecretNode :execresult
DELETE FROM secret_nodes WHERE id = ?
`

func (q *Queries) DeleteSecretNode(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteSecretNode, id)
}

const findSecretByName = `-- name: FindSecretByName :one
SELECT id, kind, parent_id, name, value, created_at, updated_at
FROM secret_nodes
WHERE name = ? AND kind = 'secret'
`

func (q *Queries) FindSecretByName(ctx context.Context, name string) (SecretNode, error) {
	row := q.db.QueryRowContext(ctx, findSecretByName, name)
	var i SecretNode
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ParentID,
		&i.Name,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSecretNode = `-- name: GetSecretNode :one
SELECT id, kind, parent_id, name, value, created_at, updated_at
FROM secret_nodes
WHERE id = ?
`

func (q *Queries) GetSecretNode(ctx context.Context, id string) (SecretNode, error) {
	row := q.db.QueryRowContext(ctx, getSecretNode, id)
	var i SecretNode
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ParentID,
		&i.Name,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllNodes = `-- name: ListAllNodes :many
SELECT id, kind, parent_id, name, value, created_at, updated_at
FROM secret_nodes
ORDER BY kind DESC, name
`

func (q *Queries) ListAllNodes(ctx context.Context) ([]SecretNode, error) {
	rows, err := q.db.QueryContext(ctx, listAllNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SecretNode
	for rows.Next() {
		var i SecretNode
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ParentID,
			&i.Name,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildNodes = `-- name: ListChildNodes :many
SELECT id, kind, parent_id, name, value, created_at, updated_at
FROM secret_nodes
WHERE parent_id = ?
ORDER BY kind DESC, name
`

func (q *Queries) ListChildNodes(ctx context.Context, parentID sql.NullString) ([]SecretNode, error) {
	rows, err := q.db.QueryContext(ctx, listChildNodes, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SecretNode
	for rows.Next() {
		var i SecretNode
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ParentID,
			&i.Name,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootNodes = `-- name: ListRootNodes :many
SELECT id, kind, parent_id, name, value, created_at, updated_at
FROM secret_nodes
WHERE parent_id IS NULL
ORDER BY kind DESC, name
`

func (q *Queries) ListRootNodes(ctx context.Context) ([]SecretNode, error) {
	rows, err := q.db.QueryContext(ctx, listRootNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SecretNode
	for rows.Next() {
		var i SecretNode
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ParentID,
			&i.Name,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSecretNodeName = `-- name: UpdateSecretNodeName :execresult
UPDATE secret_nodes SET name = ?, updated_at = ?
WHERE id = ?
`

type UpdateSecretNodeNameParams struct {
	Name      string
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdateSecretNodeName(ctx context.Context, arg UpdateSecretNodeNameParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateSecretNodeName, arg.Name, arg.UpdatedAt, arg.ID)
}

const updateSecretNodeParent = `-- name: UpdateSecretNodeParent :execresult
UPDATE secret_nodes SET parent_id = ?, updated_at = ?
WHERE id = ?
`

type UpdateSecretNodeParentParams struct {
	ParentID  sql.NullString
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdateSecretNodeParent(ctx context.Context, arg UpdateSecretNodeParentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateSecretNodeParent, arg.ParentID, arg.UpdatedAt, arg.ID)
}

const updateSecretNodeValue = `-- name: UpdateSecretNodeValue :execresult
UPDATE secret_nodes SET value = ?, updated_at = ?
WHERE id = ? AND kind = 'secret'
`

type UpdateSecretNodeValueParams struct {
	Value     []byte
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdateSecretNodeValue(ctx context.Context, arg UpdateSecretNodeValueParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateSecretNodeValue, arg.Value, arg.UpdatedAt, arg.ID)
}
