name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install and run go-toolchain
        env:
          GONOSUMCHECK: "*"
          GONOSUMDB: "*"
          GOPRIVATE: "github.com/wow-look-at-my/*"
          GOFLAGS: "-buildvcs=true"
          GH_TOKEN: ${{ secrets.PRIVATE_ORG_REPO_READ }}
          GO_TOOLCHAIN_CACHING_INTENTIONALLY_NOT_CONFIGURED: "1"
        run: |
          curl -fsSL -o /usr/local/bin/go-toolchain \
            https://github.com/wow-look-at-my/go-toolchain/releases/latest/download/go-toolchain_linux_amd64
          chmod +x /usr/local/bin/go-toolchain
          git config --global url."https://${GH_TOKEN}@github.com/".insteadOf "https://github.com/"
          go-toolchain ignore coverage
          go-toolchain
