name: CI

on:
  push:

permissions:
  contents: write
  id-token: write
  actions: read
  checks: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: wow-look-at-my/go-toolchain@v1
